version: '2'

services:
# Commit
  unit:
    image: openjdk:8u162-jdk
    mem_limit: 1570m  # jvm allocates 1/4 to max heap size
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    working_dir: /appsrc
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    command: bash -c "./gradlew clean build copyDockerFiles --no-daemon"

  app:
    build:
      context: ./backend-auth-service/build/dockerfile/
    image: thesis-authservice:snapshot

# Staging
  eurekapeer1:
    image: thesis-eurekaservice:snapshot  # TODO fixed?
#    image: localhost:5000/thesis-eurekaservice:latest
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    environment:
      - PROFILE=peer1
    ports:
      - "7761:8761"

  eurekapeer2:
    image: thesis-eurekaservice:snapshot  # TODO fixed?
#    image: localhost:5000/thesis-eurekaservice:latest
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    environment:
      - PROFILE=peer2
    ports:
      - "7762:8761"

  configservice:
    image: thesis-configservice:snapshot  # TODO fixed?
#    image: thesis-configservice:latest
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    depends_on:
      - eurekapeer1
      - eurekapeer2
    environment:
       EUREKASERVICE_URI: "http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/"
       EUREKASERVICE_PORT: "8761"
       ENCRYPT_KEY: "COMMON_SYMMETRIC_KEY"
    ports:
      - "7888:8888"

  authservice:
    image: thesis-authservice:snapshot
    mem_limit: 500m   # jvm allocates 1/4 to max heap size
    depends_on:
      - eurekapeer1
      - eurekapeer2
      - configservice
    environment:
      PROFILE: "default"
      SERVER_PORT: "9999"
      CONFIGSERVICE_URI: "http://configservice:8888"
      CONFIGSERVICE_PORT: "8888"
      EUREKASERVICE_URI: "http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/"
      EUREKASERVICE_PORT: "8761"
      ENCRYPT_KEY: "COMMON_SYMMETRIC_KEY"
    ports:
      - "7999:9999"

  staging:
    image: openjdk:8u162-jdk
    mem_limit: 1570m  # jvm allocates 1/4 to max heap size
    depends_on:
      - eurekapeer1
      - eurekapeer2
      - configservice
      - authservice
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    environment:
      EUREKASERVICE_URI_1: http://eurekapeer1:8761
      EUREKASERVICE_URI_2: http://eurekapeer2:8761
      EUREKASERVICE_PORT: 8761
      CONFIGSERVICE_URI: http://configservice:8888
      AUTHSERVICE_URI: http://authservice:9999
      ENCRYPT_KEY: "COMMON_SYMMETRIC_KEY"
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    working_dir: /appsrc
    command: bash -c "ping -c 1 eurekapeer1 && ping -c 1 eurekapeer2 && ping -c 1 configservice && ping -c 1 authservice && ./gradlew integTest --no-daemon"
