#server.port: 9999

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#server:
#  contextPath:   /auth

# logging
logging.level:
  com.netflix: WARN
  org.springframework.web: WARN
  com.kdzido.thesis: DEBUG